#import "../fragments/FeatureBlockFragment.gql"

fragment FeatureSectionFragment on FeatureSection{
    id
    blockType
    field 
    heading
    hash 
    features {              
        blockType
        field
        ...FeatureBlockFragment
    }
}
